$ANSIBLE_VAULT;1.1;AES256
33616237333230396534376232626136336138613161666536353561373563613936636635366361
3230376664613964383635663334333262646237313737610a646634303735383934343936393834
39313462363338326331613732633965303565343166623932613638353562633664383935383933
3430353933393935370a376339313334343436323130316133383136333266633463303336363134
30653036646432633534313832663333326231356539376333346361643039613533666534303262
36356361346331316633346532666533666635393361333138636161383839383737656562396636
64623363393061303034396630396531343166306431343937353730643061323332333532366331
66363139383733366664386436333838343634336232343431326566303330626334313639636262
33363932653665333938396163366231333538333639393436393837393763316538316265383035
36326439376335386366653339333165363830643062333938633030646162313365653134386338
38366234323762616663623130323965346239323132643839393432626632323530666631633932
35613666366666653238643263646339333162366639373835353232643164396432666532363564
33666338353933306238393162363833396331643331363233363461313137346136306537316664
64303762626266616365306433653266616165646363663031656537363864363833663266333733
30626262313436653461643563646131613131356536316134316136316435343937383636646330
37653263326338333139646530333033616364353538303133333064313539623634636565333434
66323631376536653037393537663236366234366538313761313736663339353136663565643332
63333832353736623837306635363930643961643064613530356233363836396161376664363238
61323062343633313665616134616638346461643434613333306266396434636461643339623830
35396135653634636536313732366231663862313832323366653063643461336662346565643331
37313933323332333463633363616238633334346461346265623037316463316536623038653136
31343634643730353934616532626366353364643435376137313537383539636361633263633966
31383463663331653762383762353839353663323636663565343532393635393165303163623739
38633730306335343963373966646234623761663232633334373662363764303937383539626436
6635
