$ANSIBLE_VAULT;1.1;AES256
35613862623834316466643337363138363333666434343262626461356432656163333637363065
3134623865326663383635373063313537666265313131370a666335333433633937316364393033
33343332623032393331313566663035353863376664326638326666353230373163323930326362
3439353937646335360a646139613761636130313931333331366162353436616239396164313763
65306463333434643437663935393265613432663832346438616638633665626139393831613136
35393537643836343362386535313836656564646133336135333439653035326137613863646638
38306263613934633933363531313532313432636137376237323737626566333561656332646332
39366233663235373239303964373466306665376566386164366164666665363461333761333462
35363262313431353031363530616138663066333766656431653133306432313433383431306162
66643364636437323731666233386132626162383033346363623534366535313630373735376137
37323266626137643234343139623131393362366464323736663735356138333365366636383062
30646636653966326461313932303932316636653462393465333631666237306236386539316363
36616239366261666462386161663538633862653865313437633239343862336532353138353639
64653434383962356136316331336163316131383864373031333933376162393035303066643935
33313331333134373631653336376663366238336231326635306234333235663538393133353434
66363633393365646162643664633736653238636431336634663732666163396661353735333937
30633231636163373633373839306331313565383565633263356666313338363039396666346230
38336366666231653139653532633761346233613666303465323136383265353131363731303639
30353662386536373761653865646263666135613531306338656664386463313663663934613136
64633637313936393364653931306634326139646532333938373362303062623334303666633039
61336538386333353163383934353236393738396261633763363539376432666661626663313934
35623132643630383639356564663439333130396238643766343963343664623633616565326633
61633139626336396439346161633064646632653064303937326335306534656665343037353839
32343131353964343466343833646334623063346239633931376132363066356638623565356366
61396163663437613034386135316334346261316536343164393934373832383361363963633964
38383732653965333064333631373165353232633361343164613630393238646161336133646562
64313063363832333038356266396162383236653834343866656666323432343562613962353066
39383133306231306365323937636566646232316332613739383939373831323930313133316463
66643231303264303264336564323931383638643363633137353062383234303035
