$ANSIBLE_VAULT;1.1;AES256
38613633633437643630323435636564646134383535363833626337376530663164353262656565
3134646166353339363666656532336337663165613137320a396631363637643065356239346438
35316332643465663562323262353139386364373864316138666131333233366366623238316131
3437383565313766340a366238623765396430303334373831383566383838623436643666323830
38643239353835393634613739653062356133643264633963393132316162396539623961633135
61613866373935356139396338613461323065336634616664646536383834323430643266363162
65363733346165326632376162636335336362336663343261373461383539643131353766316638
62323534376462373835313138653232303365633163313133363737666263633130343931306332
38626437633637343239396363366661316432643732393532393436613064323736356232666630
35636137363034383935383836663035313364313961346532326131356634346162373936646562
65333233323934663161313738323339363364346137313131353838326537363939663261333938
38353031373334386662316566353065313938336463343132633161646163656236656136653466
66666337343736386161353138343639363531353032376264363630663437386661343734636536
63363435343435613233363135383134666138633630626336643261316535623432323039303531
63353061323961653831616535393637313361613961656133393762646161613565643236383134
64333066653037346239363239616336633564623930663162666361633736653936336532616365
62306163626334396133343065633964616332353539613437333865333863626565663261656636
33663132303534303235346635383163646339623938313266353032643664396132636231666261
38393737343830656239363163326539303431316662316462653961643536353339326137326166
63396438363030366633326232316165363363656361353537343362326430613331326563396262
37396230313836663261616463616435356635653834646330333033656432616331343630356135
32343336353233323361623364393435343738653438653261646162396565393162373832323236
63626566366231613134623830376163666363326533363738313735623465663163323532633762
63373035303162376336373031643935653238623666333337306663623639613634383936326162
6639
