$ANSIBLE_VAULT;1.1;AES256
66666332666335303265623037376439616230306261613831336533636330636566353264646635
3036323830366561323933626261666131393636346537380a356633356365363163303834323062
37396238653738636438663634366432373130336431666238396130666134323439613335633265
6533646238306163310a353335613436393539613131366363383264396236656566616639353937
34333536323664633332666163326264623134393961613965363633653830626636396361366631
36336231323737613733333530633039663932363162653735356266366632383337623039333239
36323866633234373361363537376261393862386165396535383962333135366265376532373534
64633038386436373832356335646661633133313261363430303163623262666231633638363035
65653264663338353236623661663631356435643364333032333331333966356136316236396231
39383433303538663132383265623366376636643938343736313731613534343532343733613630
65316535356431353030646134396439393131306537373065663539616232323933626639663531
65313163343362366535326462343036346365366433356630303438616235623734353461616238
39326636393133313030386430613662343139643136393962653664303664656536393739656465
37313431613162393865343337653166616238376264313664633965356230333130326562363234
64623635366232626230353261353434663738663337366663316561306337363566333837303764
61636231633466653164353336396366653236636331326434353531346562366462626464373866
38656534613638356661666432336662323337383838393363613865363935326132353931666635
64393066393163636332333631383262353532383236363032653864666664386338633962363663
343136323933393131336464306265663735
