---
- name: "Create .well-known/acme-challenge directory"
  file:
    path: /var/www/certbot/.well-known/acme-challenge
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rx,o=rx

- name: "Create autoconfig directory"
  file:
    path: /var/www/autoconfig
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rx,o=rx

- name: install config file for Le's Encrypt HTTP challenge
  template:
    src: certbot.conf.j2
    dest: /etc/nginx/sites-available/certbot.conf

- name: Create symbolic link to enable our certbot config
  ansible.builtin.file:
    src: ../sites-available/certbot.conf
    dest: /etc/nginx/sites-enabled/certbot.conf
    state: link
    force: true

- name: install config file for mail autoconfig (Thunderbird, etc.)
  template:
    src: autoconfig.conf.j2
    dest: /etc/nginx/sites-available/autoconfig.conf

- name: Create symbolic link to enable our autoconfig config
  ansible.builtin.file:
    src: ../sites-available/autoconfig.conf
    dest: /etc/nginx/sites-enabled/autoconfig.conf
    state: link
    force: true
  notify: restart nginx

