---
- name: install packages
  apt:
    update_cache: yes
    name:
      - openssl
      - argon2
      - libsodium23
      - gpg
      - gpg-agent
      - gpg-wks-client
      - gpg-wks-server
      - gpgconf
      - gpgsm
      - gpgv
      - certbot
      - pwgen
      - postfix
      - postfix-mysql
      - dovecot-mysql
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
      - rspamd
      - fail2ban
      - ca-certificates
      - mutt
      - nginx
      - mariadb-client
      - nfs-common
      - bind9
      - bind9-dnsutils
      - bind9-host
      - bind9-utils
      - python3-argon2
      - python3-argon2-cffi
      - python3-inotify
      - python3-pymysql


